port:
  servlet: 8080

db:
  master:
    url: jdbc:mysql://localhost:33070/test01?useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true&treatTinyAsBoolean=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  slaver:
    url: jdbc:mysql://aliyun-ecs:33070/test01?useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true&treatTinyAsBoolean=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  shardingsphere:
    url-1: jdbc:mysql://aliyun-ecs:33070/test01?useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true&treatTinyAsBoolean=false&serverTimezone=Asia/Shanghai
    username-1: root
    password-1: root
    url-2: jdbc:mysql://aliyun-ecs:33070/test02?useSSL=false&characterEncoding=utf-8&rewriteBatchedStatements=true&treatTinyAsBoolean=false&serverTimezone=Asia/Shanghai
    username-2: root
    password-2: root

cache:
  redis:
    host: localhost
    database: 0
    password: 123
    port: 6379

    host-2: localhost
    database-2: 1
    password-2: 123
    port-2: 6379