spring:

  # 日期格式，解决日期传输到前端变成时间戳的问题
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # Spring 网络配置
  http:
    encoding:
      # 编码格式
      charset: UTF-8
      enabled: true
      force: true

  # servlet 配置
  servlet:
    # 文件上传配置
    multipart:
      # 是否支持文件上传
      enabled: true
      # 上传的文件的最大值
      max-file-size: 100MB
      # request 的最大值
      max-request-size: 100MB

  # Thymeleaf 相关配置
  # 不做前后端分离的情况下会用得到
  thymeleaf:
    # 页面类型
    mode: HTML5
    # 路径，默认 classpath:/templates/
    prefix: classpath:static/
    # 设置后缀
    suffix: .html
    # 编码格式
    encoding: UTF-8

  # 配置使用的 application-xxx.yml
  # profiles.active: local  # 单配置文件
  profiles.include: local,local-url  # 多配置文件



# 配置使用的 log4j2 文件
logging:
  config: classpath:log4j2.xml
  level.root: debug


# mybatis 配置
mybatis:
  # 下划线命名法自动转驼峰命名
  configuration.map-underscore-to-camel-case: true
  # 扫描的 mybatis mapeer 路径
  mapper-locations: classpath:/mapper/*.xml

# page helper 配置
pagehelper:
  # 自动合理化参数，如果 page 或者 pageSize 小于零了就自动查询第一页
  reasonable: true
  # 配置数据库类型
  helper-dialect: mysql


